locale = 'zh_cn';
addLangs({
	'all' : '所有',
	'All' : '所有',
	'filter members' : '过滤成员',
	'person' : '联系人',
	'close' : '关闭',
	'information' : '信息',
	'check in': '<strong>签入</strong>',
	'cannot check in': '无法签入',
	'add as new revision to': '作为新版本添加到',
	'error loading content': '加载内容错误。请稍后再试。\n如果依然存在此问题，请联系管理员。',
	'projects': '工作区',
	'administration': '管理',
	'open link': '打开链接',
	'open in new tab': '在新标签中打卡',
	'close tab': '关闭标签',
	'close other tabs': '关闭其他标签',
	'loading': '加载中...',
	'help': '帮助',
	'menu': '菜单',
	'back': '返回',
	'server could not be reached': '无法链接服务器',
	'http error': '错误{0}：{1}',
	'refesh desc': '刷新视图',
	'last updated by at': '{0}，{1}', 
	'last updated by on': '{0}，{1}', 
	'last updated by': '最后更新者',
	'close this tag' : '关闭此标签',
	'you' : '您',
	'checkout notification' : '签出通知',
  	'document checked out by' : '此文档目前被{0}签出了',
  	'checkout confirmation' : '签出确认',
  	'checkout and download' : '签出并下载',
  	'download only' : '仅签出',
  	'checkout recommendation' : 'Are you planning on editing this document? If so, it is recommended that you checkout the document when downloading',
  	'mark as read': '标为已读',
  	'mark as unread': '标为未读',
  	'mark as read desc': '标示所选对象为已读',
  	'confirm inherit permissions': '您想要从父工作区继承所有权限吗？',
  	'filters': '过滤器',
	/* file manager */
	'by': '创建者',
	'name': '名字',
	'project': '工作区',
	'user': '用户',
	'tag': '标签',
	'tags': '标签',
	'last update': '最后更新者',
	'created on': '创建时间',
	'download': '下载',
	'properties': '属性',
	'revisions and comments': '修订版本及评论',
	'slideshow': '幻灯',
	'view slideshow': '查看幻灯',
	'add tag': '添加标签',
	'enter the desired tag': '输入想要的标签',
	'new': '新建',
	'create an object': '创建对象',
	'document': '文档',
	'spreadsheet': '表格',
	'presentation': '幻灯',
	'upload': '上传',
	'upload a file': '上传文件',
	'tag selected objects': '标签选中的对象',
	'delete': '删除',
	'empty trash can' : '清空回收站',
	'empty trash can desc' : 'Permanently delete all trashed objects',
	'delete selected objects': 'Delete selected objects',
	'confirm delete object': 'Are you sure you want to delete the selected object(s)?',
	'confirm delete contact': 'Are you sure you want to delete this contact?',
	'confirm delete company': 'Are you sure you want to delete this company?',
	'confirm delete event': 'Are you sure you want to permanenetly delete this event? \nInvitations to this event will also be deleted. \nAfter deleting an event other users won\'t be able to see it in their calendars'   ,
	'confirm delete file': 'Are you sure you want to delete this file?',
	'confirm delete mail content': 'Are you sure you want to delete this email?',
	'confirm delete mail account': 'Are you sure that you want to delete this mail account?',
    'confirm delete milestone': 'Are you sure you want to delete this milestone?',
	'confirm delete chart': 'Are you sure you want to delete this chart?',
	'confirm delete message': 'Are you sure you want to delete this note?',
	'confirm delete task list': 'Are you sure you want to delete this task list, along with its subtasks?',
	'confirm delete webpage': 'Are you sure you want to delete this weblink?',
	'confirm delete workspace': '您确定要删除工作区 \'{0}\'吗？',
	'confirm delete project': 'Are you sure that you want to delete this workspace and all related data (messages, tasks, milestones, files...)?',
	'confirm cancel work timeslot': 'Are you sure you want to cancel the current timeslot?',
	'more': '更多',
	'more actions': '更多操作',
	'more actions on first selected object': 'More actions on first selected object',
	'displaying files of': 'Displaying files {0} to {1} of {2}',
	'no files to display': '暂无文件',
	'no tasks to display': '暂无任务',
	'refresh desc': '刷新视图',
	'templates desc': '管理模版',
	'templates': '模版',
	'no users to display' : '暂无用户',
	'fixed user':'固定用户',
	'parametric user':'Parametric user',
	'string': '字符串',
	'add parameter': '添加参数',
	'edit workspace': '编辑选中的工作区',
	'company': '公司',
	'companies': '公司',
	'checkin': '签入',
	'checkout': '签出',
	'checked out by': '被{0}签出',
	'add file checked out by': '{0}已被{1}签出。',
	'extract': '解压缩',
	'extract files': '解压缩文件',
	'compress': '压缩',
	'compress selected files': '压缩所选文件',
	'add files to zip': '添加到zip文件中',
	'new compressed file': '新压缩文件',

	'song': '歌曲',
	'artist': '歌手',
	'album': '专辑',
	'year': '年份',
	'playlist': '播放列表',
	'playlists': '播放列表',
	'unknown': '未知',
	'previous': '上一首',
	'play': '播放',
	'pause': '暂停',
	'stop': '停止',
	'next': '下一首',
	'mute': '静音',
	'unmute': '取消静音',
	'load from current workspace': '从当前工作区载入',
	'load playlist from file': '从文件中载入播放列表',
	'save playlist to file': '保存播放列表到文件',
	'clear playlist': '清除播放列表',
	'remove selected from playlist': '从播放列表中移除所选文件',
	'shuffle playlist': '缓冲播放列表',
	'toggle loop playlist': '切换循环列表',
	'play this file': '播放此文件',
	'queue': '队列',
	'queue this file': '将文件加入播放列表队列',
	'must choose a file': '您必须选择一个文件',
	'file has no valid songs': '您选择的文件中没有可播放歌曲',

	'error': '错误',
	'success': '成功',
	'unexpected server response': '意外的服务器响应',
	'new tab': 'New Tab',
	'file revision comments required': '文件修订版本评论是必须的。',
	
	/* dashboard */
	'dashboard': '首页',
	'upload file': '上传文件',
	'contact': '联系人',
	'event': '事件',
	'task': '任务',
	'milestone': '里程碑',
	'refresh': '刷新',
	'author': '作者',
	
	/* tabs */
	'overview': '首页',
	'messages': '便签',
	'contacts': '联系人',
	'persons': '联系人',
	'calendar': '日程安排',
	'tasks': '任务管理',
	'web pages': '地址库',
	'documents': '文档管理',
	'account': '帐号',
	'administration': '系统管理',
	'search': '搜索',
	'webpage': '网址库',
	'message': '便签',
	
	'workspaces': '工作区',
	'all': '所有',
	'all customers': '所有客户',        
	'create a workspace': '创建新工作区',
	'delete selected workspace': '删除所选工作区',
	
	/* object picker */
	'select an object': '请选一个对象...',
	'filter': '过滤器',
	'all ws': '所有工作区',
	'all type': '所有类型',
	'all tag': '所有标签',
	'view': '查看',
	'details': '详情',
	'icons': '图标',
	'displaying objects of': '对象{0} - {1}，总计{2}',
	'no objects to display': '暂无对象',
	'ok': '确定',
	'cancel': '取消',
	
	/* contact manager*/
	'company': '公司',
	'add new contact': '添加新联系人',
	'displaying contacts of': '联系人{0} - {1}，总计{2}',
	'no contacts to display': '暂无联系人',
	'delete selected contacts': '删除所选联系人',
	'confirm delete contacts': '您确定要删除所选联系人?',
	'role': '角色',
	'tag selected contacts': '所选联系人标签',
	'department': '部门',
	'email2': 'Email 2',
	'email3': 'Email 3',
	'workWebsite': '工作网址',
	'workAddress': '工作地址',
	'workPhone1': '工作电话1',
	'workPhone2': '工作电话2',
	'homeWebsite': '家庭网址',
	'homeAddress': '家庭地址',
	'homePhone1': '家庭电话1',
	'homePhone2': '家庭电话2',
	'mobilePhone': '手机',
	'edit selected contact': '编辑所选联系人',
	'edit selected object': '编辑所选对象',
	'assign to project': '分派到工作区',
	'assign contact to project': '编辑联系人分派',
	'import': '导入',
	'export': '导出',
	'import/export': '导入/导出',
	'import - export': '联系人导入/导出',
	'not csv file continue': '所选文件不是.csv文件\nAre you sure you want to continue?',
	'from csv': '从csv',
	'from vcard': '从VCard',
	'to csv': '到csv',
	'to vcard': '到VCard',
	'to vcard all' : '所有到VCard',
	
	/* webpage manager*/
	'description': '描述',
	'title': '标题',
	'add new webpage': '添加新网址',
	'displaying webpages of': '网址{0} - {1}，总计{2}',
	'no webpages to display': '暂无网址',
	'delete selected webpages': '删除所选网址',
	'confirm delete webpages': '您确定要删除所选网址吗？',
	'tag selected webpages': '标签选中的网址',
	'edit': '编辑',
	'edit selected webpage': '编辑所选网址',
	
	/* message manager */
	'text':'内容',
	'date':'日期',
	'add mail account':'添加邮件帐号',
	'classify':'归类',
	'classify email':'归类邮件',
	'add new message':'新建便签',
	'view by account': '按帐号查看',
	'view emails by account': '按帐号查看邮件',
	'edit account': '编辑帐号',
	'edit email account': '编辑邮件帐号',
	'email actions': '邮件操作',
	'more email actions': '更多邮件操作',
	'view unclassified': '查看未归类',
	'view unclassified emails': '查看未归类邮件',
	'all accounts': '所有帐号',
	'view all accounts': '查看所有帐号',
	'hide messages': '隐藏便签',
	'show messages': '显示便签',
	'view': '查看',
	'view all': '查看所有',
	'all emails': '所有邮件',
	'unclassified emails': '未归类邮件',
	'view options': '查看选项',
	'check mails' : '收邮件',
	'emails' : '邮件',
	'create an email' : '新建邮件',
	'checking email accounts' : '检查邮件帐号...',
	'folder' : '文件夹',
	'yes' : '是',
	'no' : '否',
	'delete account emails': '同时删除邮件',
	'select' : '选择',
	'read' : '阅读',
	'classified' : '已分类',
	'accounts' : '帐号',
	'account options' : '帐号选项',
	'to' : '到',
	'view by state' : '按状态',
	'view by account' : '按帐号', 
	'view by classification' : '按分类',
	'outbox' : '发件箱',
	'mail sent msg' : '邮件已发送。',
	'send outbox' : '发送发件箱中邮件',
	'send outbox title' : '发送发件箱中邮件',
	'sending outbox mails' : '正在发送发件箱中邮件...', 
        
	'filter workspaces': '筛选工作区...',
	'filter tags': '筛选标签...',
	'alphabetical': '按字母顺序',
	'most active': '最活跃的',
	'alphabetical desc': 'Sort in alphabetical order',
	'most active desc': 'Sort by most activity',
	'sort desc': 'Sort the view',
	
	//'no objects message': 'There are no \'{0}\' in \'{1}\'',
	'no objects message': '{0}不存在哦',
	'no more objects message': 'There are no more \'{0}\' to display',
	'no objects with tag message': 'There are no {0} tagged as \'{2}\' in \'{1}\'',
	'objects': 'Objects',
	
	'checkout description': 'Lock this file for editing',
	'undo checkout description': 'Make this file available',
	'checkin description': 'Check in new version of this file',
	
	'created by on': 'Created by {0} on {1}',
	
	/*  */
	'write' : '撰写',
	'write new mail' : '撰写邮件',
	'email': '邮件',
	'attach contents' : '附加内容',
	'email tab': '邮件',
	'weblink': '网址',
	'webpage': '网址',
	'task': '任务',
	'milestone': '里程碑',
	'emailunclassified': '邮件',
	'file': '文件',
	'contact': '联系人',
	'event': '事件',
	
	'debug': '调试',
	'incomplete': '不完全的',
	'complete': '完全的',
	'do complete': '执行完全的',
	'late': '迟',
        'status': '状态',
	'event status': '事件状态',
        'task status': '任务状态',
        'hide all tasks': '隐藏所有任务',
	
	'open link in new window' : '在新窗口中打开 \'{0}\'',
	
	'wschooser desc from': '可用的工作区',
	'wschooser desc to': '对象的工作区',

	'updated by': '更新者',
	'created by': '创建者',
	'view as dashboard': '作为首页查看',
	/* Events*/
	'subject':'主题',
	'add event':'添加事件',
	'next month':'下一月',
	'prev month':'上一月',
	'today':'今天',
	'pick a date':'到',
	'month':'月',
	'month view':'月视图',
	'week':'周',
	'week view':'周视图',
	'day':'日',
	'day view':'日视图',
	'by state':'按状态',
	'view pending response':'待处理回复',
	'view will attend':'参加',
	'view will not attend':'不参加',
	'view maybe attend':'可能',
	'by user':'按用户',
	'add new event':'添加新事件',
	'prev':'上一个',
	'next':'下一个',
	'my calendar': '我的日历',
	'edit event details': '编辑事件详情',
	'duration': '时长',
	'this field is required': '此字段必填',
	
	/* Charts */
	'reporting' : '报表',
	'add new chart' : '添加新图表',
	'delete selected charts' : '删除所选图表',
	'confirm delete charts' : 'Are you sure you want to delete the selected charts?',
	'edit selected chart' : 'Edit selected chart',
	'tag selected charts' : 'Tag the selected charts',
	'displaying charts of': 'Displaying charts {0} to {1} of {2}',
	'no charts to display' : 'There are no charts to display',
	'charts' : '图表',
	'unlock': '使用中',
	'lock': '可用',
	'edit this document': '编辑此文档',
	
	/* tasks */
	'assigned to': 'Assigned to',
	'assign to': 'Assign to',
	'add subtask to': 'Add subtask to \'{0}\'',
	'add task to': 'Add task to \'{0}\'',
	'add task': 'Add task',
	'add milestone': 'Add milestone',
	'add new task': 'Add new task',
	'add new milestone': 'Add new milestone',
	'confirm delete task': 'Are you sure you want to delete this task and all of its subtasks?',
	'confirm delete milestone': 'Are you sure you want to delete this milestone?',
	'due date': 'Due date',
	'milestone delete tip': 'Delete this milestone',
	'milestone edit tip': 'Edit this milestone',
	'milestone check tip': 'Complete/open this milestone',
	'milestone expand tip': 'Show/hide this milestone\'s tasks',
	'milestone view tip': 'Milestone: {0} (Click to view more)',
	'task delete tip': 'Delete this task',
	'task edit tip': 'Edit this task',
	'task check tip': 'Complete/open this task',
	'task expand tip': 'Show/hide this task\'s subtasks',
	'task view tip': 'Task: {0} (Click to view more)',
	'task move down tip': 'Move task down one place',
	'dont assign': 'Don\'t assign',
	'overdue': 'Overdue',
    'active': 'Active',
    'my active': 'My active',
    'my subscribed': 'My subscribed',
	
	'new milestone': 'New milestone',
	'new task': 'New task',
	'error adding task': 'Error adding task',
	'error adding milestone': 'Error adding milestone',
	'error fetching tasks': 'Error fetching tasks',
	
	'confirm unload page': 'You have unsaved data. If you leave the page you will lose any unsaved data.',
	'confirm leave panel': 'You have unsaved data. If you proceed you will lose any unsaved data.\nProceed?',
	'unread emails': 'Unread emails',
	'mark read': 'Mark as read',
	'mark unread': 'Mark as unread',
	'from': 'From',
	'draft': 'Draft',
	'create contact or client company':'创建联系人或者客户公司',
	'mail sent': 'Mail sent',
	
	'click to remove': 'Click to remove',
	
	'confirm merge tags': 'Are you sure you want to merge tag \'{0}\' with tag \'{1}\'?\n(Once the tags are merged they can\'t be unmerged)',
	'save': 'Save',
	'choose a filename': 'Choose a filename',
	'rename tag': 'Rename tag',
	'enter a new name for the tag': 'Enter a new name for the tag',
	'duplicate company name':'<span style="color:#F00">A company with the name \'{0}\' already exists.&nbsp;</span><a href="#" style="text-decoration:underline" onclick="og.selectCompany(\'{1}\',{2})">Select this company</a>, or choose a different name',
	'inbox':'Inbox',
	'sent':'Sent',
	'unread': 'Unread',
	'confirm unclassify emails': 'Are you sure you want to unclassify the selected emails?',
	
	'confirm remove tags': 'Are you sure you want to remove all tags from the selected objects?',
	'remove tags': 'Remove tags',
	
	'more options': 'More options',
	'login': 'Login',
	'username': 'Username',
	'password': 'Password',
	'remember me': 'Remember me',
	'completed': 'Completed',
	'notify': 'Notify',
	'hours worked': 'Hours worked',
	
	'completed by': 'Completed by',
	'assigned by': 'Assigned by',
	'priority' : 'Priority',
	'unclassified': 'Unclassified',
	'ungrouped': 'Unclassified',
	'unassigned': 'Unassigned',
	'anyone': '任何一个人',
	'everyone': '每个人',
	'pending': 'Pending',
	'group by': 'Group by',
	'order by': 'Order by',
	'workspace':'工作区',
	'start date': 'Start date',
    'progress' : 'Progress',
	'task name': 'Task name',
	'show': 'Show',
	'time': 'Time',
    'time estimates': 'Estimated time',
    'time estimate': 'Estimated time',
	'dates': 'Dates',
	'empty milestones': 'Empty milestones',
	'select user or group': 'Select user or group',
	'select milestone': 'Select milestone',
	'select priority': 'Select priority',
	'low':'Low',
	'normal':'Normal',
	'high':'High',
	'urgent':'Urgent',
	'me': 'Me',
	'complete selected tasks': 'Complete the selected tasks',
	'unclassified' : 'Unclassified',
	'earlier than one year': 'Earlier than 1 year',
	'last year' :'3 months to 1 year ago',
	'last three months' : '1 to 3 months ago',
	'last month' : '2 weeks to 1 month ago',
	'last two weeks' : '1 week to 2 weeks ago',
	'last week' : 'Yesterday to 1 week ago',
	'yesterday' : 'Yesterday',
	'today' : 'Today',
	'tomorrow' : 'Tomorrow',
	'one week' : 'In one week',
	'two weeks' : 'In two weeks',
	'one month' : 'In 2 weeks to 1 month',
	'three months' : 'In 1 to 3 months',
	'one year' : 'In 3 months to 1 year',
	'later than one year' : 'Later than one year',
	'start' : 'start',
	'due' : 'due',
	'add subtask': 'Add a new subtask',
	'completed by name on' : 'Completed by {0} on {1}',
	'completed by' : 'Completed by',
	'show more tasks number' : 'Show more ({0})...',
	'start_work': 'Start working on this task',
	'close_work': 'Stop working on this task',
	'pause_work': 'Pause work on this task',
	'resume_work': 'Resume working on this task',
	'close work': 'Stop work',
	'time worked' : 'Time worked',
	'hours' : 'hours',
	'complete this task' : 'Complete this task',
	'reopen this task' : 'Reopen this task',
  	'reopen' : 'Reopen',
	'assign': 'Assign',
	'assigning to' : 'Assigning to',
	'success add task' : 'Task added successfully',
	'invalid action' : 'Invalid action',
	'hide others' : 'Hide others',
	'hide other groups' : 'Hide other groups',
	'show all' : 'Show all',
	'show all groups' : 'Show all the groups',
	
	'send notification' : 'Send email notification',
	'all options': 'All options',
	'click to change workspace': 'Click to change workspace',
	
	'month 1': 'January',
    'month 2': 'February',
    'month 3': 'March',
    'month 4': 'April',
    'month 5': 'May',
    'month 6': 'June',
    'month 7': 'July',
    'month 8': 'August',
    'month 9': 'September',
    'month 10': 'October',
    'month 11': 'November',
    'month 12': 'December',
    
    'monday': 'Monday',
  	'tuesday': 'Tuesday',
  	'wednesday': 'Wednesday',
  	'thursday': 'Thursday',
    'friday': 'Friday',
  	'saturday': 'Saturday',
  	'sunday': 'Sunday',
  	'comment': 'Comment',
  	
  	'change user': 'Change user',
  	'start work': 'Start work',
  	'click to change workspace': 'Click to change workspace',
  	'add a new task to this group': 'Add a new task to this group',
   	'login dialog desc': 'Your session expired due to inactivity. Fill in this form to log back in.',
   	'user not found' : 'User not found (id:{0})',
  
  	'date format' : 'm/d/Y',
  	'date format alternatives' : 'm/d/y|n/j/Y|n/j/y|m/j/y|n/d/y|m/j/Y|n/d/Y',
	'warning start date greater than due date': 'Warning: the start date is later than the due date',
  	
	'event start time': 'Time',
	'all day event': 'All day',
	'confirm repeating event edition': 'Editing this repeating event will modify every past and future events related.\nAre you sure you want to edit this event?',
	
  	'choose an image': 'Choose an image',
  	'sort by': 'Sort by',
  	'file size': 'File size',
  	'last modified': 'Last modified',
  	'image name': 'Image name',
  	'size': 'Size',
  	'completed on': 'Completed on',
  	
  	'save changes' : 'Save changes',
  	'no filter' : 'No filter',
  	'nothing (groups)' : 'Nothing',
  	'none' : 'None',
  	'new task time report': 'New task time report',
  	'no images match the specified filter': 'No images match the specified filter',
  	
  	'print' : 'Print',
        'print calendar' : 'Print calendar',
  	
  	'no deleted objects message': 'There are no deleted {0} in \'{1}\'',
	'no deleted objects with tag message': 'There are no deleted {0} tagged as \'{2}\' in \'{1}\'',
	'deleted on': 'Deleted on',
	'deleted by': 'Deleted by',
	'trash': '回收站',
	'restore': '恢复',
	'restore selected objects': 'Restore selected objects',
	'delete selected objects permanently': 'Delete the selected objects permanently',
	'confirm delete objects permanently': 'Once deleted you won\'t be able to bring these objects back.\nAre you sure you want to delete the selected objects permanently?',
	
	'n/a': '<acronym title="Not Available">n/a</acronym>',
	'move to trash': 'Move to trash',
    'move selected objects to trash': 'Move selected objects to trash',
    'confirm move to trash': 'Are you sure you want to move the selected objects to the trash can?',
    'confirm restore objects': 'Are you sure you want to restore the selected objects?',
    
    'file_revision': 'File revision',
    'trash emptied periodically': 'Objects left in the trash more than {0} days will be deleted.',
    'remove': 'Remove',
    'object type not supported': 'This object type is not supported for templates', 
    'confirm delete timeslot' : 'Are you sure you want to permanently delete this timeslot?',
    'confirm delete permanently': 'Are you sure you want to delete this object?',
    
    'confirm delete permanently company': 'Are you sure you want to permanently delete this company?\nNote that all company users will also be deleted.',
    'confirm move to trash company': 'Are you sure you want to delete this company?\nNote that all company users will also be deleted.',
    
    'no items selected' : 'No items selected',
    'error adding timeslot' : 'An error occurred while adding the timeslot',
    'confirm unclassify email' : 'Are you sure you want to unclassify this email?\nThe email will be removed from the workspaces ant its attachments will not appear in Documents tab.',
    
    'no due date': 'No due date',
    'no start date': 'No start date',
    'untagged': 'Untagged',
    'download selected file': 'Download selected file',
    'edit selected file properties': 'Edit selected file\'s properties',
    'update file':'Update File',
    'you must enter a name': 'You must enter a name',
    'sort tags': 'Sort tags',
    'sort tags alphabetically': 'Alphabetically',
    'sort tags by count': 'By Count',
    'actions' : 'Actions',
	'show more' : 'Show more',
    'confirm template with no objects': 'Are you sure you want to create a template with no objects in it? (You can add objects to it later)',
    'confirm delete tag': 'Are you sure you want to completely delete the tag \'{0}\'?',
    'delete tag': 'Delete tag',
    
    'reminder_popup': 'Pop-up message',
    'reminder_email': 'E-mail',
    'minutes': 'minutes',
    'weeks': 'weeks',
    'days': 'days',
    'months': 'months',
    'before': 'before',
    'remove object reminder': 'Remove reminder',
    'apply to subscribers': 'Apply to all subscribers',
    
    'must choose company': 'You must choose a company',
    'contact import - export': '联系人导入/导出',
    'calendar import - export': 'Calendar import and export',
    'view weblink': 'View web link',
    
    'save as a new document' : 'Save as a new document',
    'add' : 'Add',
    'no results found' : 'No results found',
    'contact is already assigned' : 'The contact is already assigned',
    'confirm remove contact' : 'Are you sure you want to remove {0}?',
    'role for this contact' : 'Role for this contact',
    
    'print all groups': 'Print all groups',
    'print this group': 'Print this group',
    'new version notification title': 'New version',
    	
    /* Custom properties*/
    'numeric' : 'Numeric',
    'boolean' : 'Boolean',
    'list' : 'List',
    'table' : 'Table',
    'values comma separated': 'Values (comma separated)',
    'columns comma separated': 'Columns (comma separated)',
    'default value' : 'Default value',
    'checked': 'Checked?',
    'required' : 'Required?',
    'multiple values' : 'Multiple values?',
    'visible by default' : 'Visible by default?',
    'add custom property' : 'Add custom property',
    'delete custom property confirmation': 'Are you sure you want to delete the custom property?',
    'undo': 'Undo',
    'confirm discard changes': 'Discard changes?',
    'custom property deleted': 'This custom property and all its values are going to be deleted',
    'custom property name empty': 'Custom property names cannot be empty',
    'custom property values empty': 'You must enter values for custom property: {0}',
    'custom property wrong default value': 'Default value must be one of the comma separated values for custom property: {0}',
    'custom property duplicate name': 'Custom properties must have unique names: {0}',
    'custom property invalid numeric value': 'Default value must be a number for custom property: {0}',
    'value cannot be empty': 'Value cannot be empty',
    'value must be numeric': 'Value must be numeric',
    'memo': 'Memo',
    'add value': 'Add value',
    	
    /* Custom Reports */
    'group by': 'Group by',
    'delete condition confirmation': 'Are you sure you want to delete the condition?',
    'delete report confirmation': 'Are you sure you want to delete the report?',
  	'object type not selected': 'An object type must be selected to add a condition',
  	'condition deleted': 'This condition is going to be deleted',
  	'field': 'Field',
  	'condition': 'Condition',
  	'value': 'Value',
  	'parametrizable': 'Parameter',
  	'date format': 'mm-dd-yyyy',
  	'like': 'Like',
  	'not like': 'Not like',
  	'equals': 'Equal to',
  	'not equals': 'Not equal to',
  	'true': 'True',
  	'false': 'False',
  	'ends with': 'Ends with',
  	'report cols not selected': 'There are no columns selected for the report',
  	'no report conditions': 'There are no conditions for the report',
  	'condition value empty': 'You must enter a value for the condition of field {0}',
  	'condition value not numeric': 'The value of field {0} must be numerical',
  	
  	'milestones': 'Milestones',
  	'no subject' : 'No subject',
  	
  	'value is already in the list' : 'The value is already on the list',
  	'click to drag task': 'Click and hold to drag this task',
  	'click to drag': 'Click and hold to drag',
  	
  	'parameter name empty': 'Parameter name cannot be empty',
  	'parameter name exists': 'There is another parameter with the entered name',
  	'object exists in template': 'Object already exists in template',
  	'edit object property': 'Edit object property',
  	'fixed date': 'Fixed date',
  	'parametric date': 'Parametric',
  	'no parameters in template': 'There are no date parameters defined for this template',
  	'open property editor': 'Open property editor',
  	'template parameters': 'Parameters',
  	'template property already selected': 'The selected property is already being used',
    'no sender': 'No sender',
    	
   	/* Linked Objects*/
    'linkedobjects':'Linked Objects',
    'unlink':'Unlink',
    'link':'Link',
    'unlink object':'Unlink Object',
    'link object':'Link Objects',
   	'change parent':'Change Object',
   	'confirm unlink objects' : 'Are you sure you want to unlink the selected object(s)?',
   	
   	'repetitive task':'Repetitive task',
    
    'move to workspace': 'Move to workspace',
    'keep old workspaces': 'Keep workspaces',
    'move to workspace or keep old ones': 'Move to or keep old ones and add',
    'do you want to move objects to this ws or keep old ones and add this ws': 'Do you wanto to move the selected object(s) to this workspace or keep old ones and add this workspace?',
    'classify mail attachments': 'Classify mail attachments',
    'do you want to classify the unclassified emails attachments': 'Do you want to classify the attachments?',
    
    'tag selected events': 'Tag selected events',
    'edit selected event': 'Edit selected event',
    'apply milestone to subtasks': 'Apply Milestone to Subtasks',
  	'apply workspace to subtasks': 'Apply Workspace to Subtasks',
  	
	'click here to download the csv file': 'Click here to download the csv file.',
	
	'junk': '垃圾箱',
	'you must select the contacts from the grid': '您必须选择要导出的联系人。',
	'reply mail': '回复',
	'reply to all mail': '回复所有',
	'forward mail': '转发',
  	
  	'archive': '存档',
  	'unarchive': '取消存档',
  	'archived objects': '存档对象',
  	'archive selected object': 'Archives the selected objects',
  	'unarchive selected objects': 'Unarchives the selected objects',
  	'confirm archive selected objects': 'Are you sure you want to archive the selected objects?',
  	'confirm unarchive selected objects': 'Are you sure you want to unarchive the selected objects?',
  	'confirm archive object': 'Are you sure you want to archive this object?',
  	'confirm unarchive object': 'Are you sure you want to unarchive this object?',
  	'archived on': 'Archived on',
  	'archived by': 'Archived by',
  	'is archived': 'Is Archived',
	'no archived objects message': 'There are no archived {0} in \'{1}\'',
	'no archived objects with tag message': 'There are no archived {0} tagged as \'{2}\' in \'{1}\'',
  	
  	'task milestone does not belong to workspace' : 'Task\'s milestone does not belongs to destination workspace, if you continue task will be removed from its milestone. Are you sure you wish to continue?',
  	'task milestone workspace inconsistency' : 'NOTICE: this action will set the task\'s workspace to that of the selected milestone. Are you sure you wish to continue?',

  	'autoconfig gmail message' : 'Gmail autoconfiguration detected. <br> Remember you have to enable IMAP service for your gmail account. More information <a href="http://mail.google.com/support/bin/answer.py?answer=77695" class="internallink" target="_blank">here</a>',
  	'autoconfig hotmail message' : 'Hotmail autoconfiguration detected',
  	'autoconfig ymail message' : 'Yahoo Mail autoconfiguration detected. <br> In order to be able to use POP3 services you must own a Yahoo Plus account. More information <a href="http://overview.mail.yahoo.com/enhancements/mailplus" class="internallink" target="_blank">here</a>',
  	'autoconfig rocketmail message' : 'Yahoo Mail autoconfiguration detected. <br> In order to be able to use POP3 services you must own a Yahoo Plus account. More information <a href="http://overview.mail.yahoo.com/enhancements/mailplus" class="internallink" target="_blank">here</a>',
  	'autoconfig yahoo message' : 'Yahoo Mail autoconfiguration detected. <br> In order to be able to use POP3 services you must own a Yahoo Plus account. More information <a href="http://overview.mail.yahoo.com/enhancements/mailplus" class="internallink" target="_blank">here</a>',
  		
  	//concurrence
  	'allready updated object' : 'Someone has updated this object while you were editing it.',
  	'allready updated object desc' : 'Do you want to merge the changes? <br><br> Choose <strong>Yes</strong> to see the object on a new tab to compare it with your current changes.<br><br> Choose <strong>No</strong> to close this window and overwrite the changes.',
  	
  	'updated on' : 'Updated on',
  	'delete all tag': 'Delete all tags',
  	'mark as': 'Mark as ...',
  	'mark as desc': 'Mark selected items as Read/Unread',
  	
  	'filter users and groups': 'Filter users and groups...',
  	'users': 'Users',
  	'groups': 'Groups',
  	'no recipient': 'No recipient',
  	'object type' : 'Object type',
  	'applies to' : 'Applies to:',
  	'select co types to apply' : 'Select the object types you wish to apply the property',
  	'write an email to contact': 'Write an email to {0}',
  	'quick upload desc': 'Link a new file from your computer',
  	'switch format warn': 'Switching to text will discard all HTML formatting. Continue?',
  	
  	'assign contact role on workspace': '为联系人分配工作区中的角色',
  	'assign roles': '分配角色',
  	'expand': '展开',
  	'collapse': '关闭',
  	'warning': '警告',
  	'new email in conversation text': 'There\'s a new email in the conversation you are replying to. Do you want to send the email anyway or view the new email in a new tab?',
  	'send anyway': '仍然发送',
  	'view new email': '查看新邮件',
  	'apply assignee to subtasks': '应用被分派人到子任务',
   
    'confirm delete permanently company': 'Are you sure you want to permanently delete this company?\nNote that all company users will also be deleted.',
    'confirm move to trash company': 'Are you sure you want to delete this company?\nNote that all company users will also be deleted.',
    
    'work week': '工作日',
    'work week view': '工作日',
    
    'mark spam': 'Mark as SPAM',
    'mark ham': 'Mark as not SPAM',
    
    'select all tasks': 'Select all tasks',
    'add object subtype': 'Add object subtype',
    'delete object subtype': 'Delete object subtype',
    'delete object subtype warning': 'If you delete this subtype it will be removed from all objects that have it set. Are you sure you want to delete this subtype?',
    'object subtype deleted': 'Subtype deleted. {0}',
    
    'context': '所属关系',
    'none selected': '未选择',
    'select context members': 'Select related members',
    'member fields': '成员字段',
    'must be numeric': '{0} must be numeric',
    'new member': '新成员',
    'view more': '查看更多',
    'type' : '类型',
  	'estimated' : '估计',
  	'this task has x pending tasks': 'This task has {0} pending open tasks',
  	'this task has no pending dependencies and can be completed': 'This task has no pending dependencies and can be completed',
  	'you must select a member from the following dimensions': 'To perform this action you have to select a member of these dimensions: {0}',
  	'archived' : '存档',
  	'dimensions' : '组织',
  	'all workspaces' : '所有工作区',
  	'all tags' : '所有标签',
  	'see more' : '更多',
  	'new person' : '新联系人',
  	'new company' : '新公司',
  	'in' : 'in',
  	'fee' : '费用',
  	'less info' : 'Less Information',
  	'more info' : 'More Information',
  	'email already taken by' : 'Email already taken by {0}',
  	'passwords dont match' : 'Passwords don\'t match',
  	'password value missing' : 'Password required',
  	'confirm disable user' : 'The User will be disabled. Continue?',
  	'confirm delete user' : 'Are you sure that you want to delete this user account?',
	'add sub task' : 'Add subtask',
        'do you want to mantain the current associations of this obj with members of': 'Do you want to mantain the current associations of this object with {0}?',
        
        'sync' : '同步',
        'delete calendar' : '删除日历？',      
        'delete calendar events' : 'Events within Feng Office related to the calendar will be deleted. Enable the checkbox on your right if you also want to delete them from Google Caelndar.',
        
        'tasks related' : 'Related tasks',
        'apply changes to' : 'Apply changes to:',
        'only this task' : 'Only this task',
        'this task alone and all to come forward' : 'This task and all to come forward',
        'all tasks related' : 'All tasks related',
        'accept' : '接受',
        'events related' : 'Related events',
        'only this event' : 'Only this events',
        'this event alone and all to come forward' : 'This events alone and all to come forward',
        'all events related' : 'All events related',
        
        'add new workspace': 'Add new workspace',
        'edit selected workspace': 'Edit selected workspace',
        'delete selected workspace_': 'Delete selected workspace',
        'delete workspace warning': 'Are you sure you want to move the selected workspace to the trash can?',
        
        'complete task and subtask' : 'This task contains subtasks which are still pending.<br/>Would you like to complete them too?',
        'option repetitive title popup' : 'This task is already completed. <br/>Do you wish to:',
        'option repetitive only task' : 'Modify this task data?',
        'option repetitive pending task' : 'Modify all task series? (Edit upcoming pending task)'
});
