locale = 'zh_cn3';
addLangs({
	'all': '所有',
	'All': '所有',
	'filter members': '筛选',
	'person': '联系人',
	'close': '关闭',
	'information': '信息',
	'check in': '签入',
	'cannot check in': '无法签入',
	'add as new revision to': '作为新版本添加到',
	'error loading content': '加载内容时出错。请稍后重试。\n如果仍旧有问题，请联系管理员。',
	'projects': '工作区',
	'administration': '系统管理',
	'open link': '打开链接',
	'open in new tab': '在新页签中打开',
	'close tab': '关闭页签',
	'close other tabs': '关闭其他页签',
	'loading': '系统加载中...',
	'help': '帮助',
	'menu': '菜单',
	'back': '返回',
	'server could not be reached': '服务器无法访问',
	'http error': '错误 {0}：{1}',
	'refesh desc': '刷新视图',
	'last updated by at': '{0}，{1}',
	'last updated by on': '{0}，{1}',
	'last updated by': '最后更新者',
	'close this tag': '关闭标签',
	'you': '你',
	'checkout notification': '签出提示',
	'document checked out by': '此文档目前被{0}签出。',
	'checkout confirmation': '签出确认',
	'checkout and download': '签出并下载',
	'download only': '仅签出',
	'checkout recommendation': '您是否打算编辑此文档呢？如果是，建议您下载时签出此文档。',
	'mark as read': '标为已读',
	'mark as unread': '标为未读',
	'mark as read desc': '将所选对象标为已读。',
	'confirm inherit permissions': '您是否想从父工作区中继承所有权限呢？',
	'filters': '筛选器',
	'by': '创建者',
	'name': '名称',
	'project': '工作区',
	'user': '用户',
	'tag': '标签',
	'tags': '标签',
	'last update': '最后更新',
	'created on': '创建时间',
	'download': '下载',
	'properties': '属性',
	'revisions and comments': '版本和评论',
	'slideshow': '幻灯片',
	'view slideshow': '查看幻灯片',
	'add tag': '添加标签',
	'enter the desired tag': '输入要添加的标签',
	'new': '新建',
	'create an object': '创建对象',
	'document': '文档',
	'spreadsheet': '电子表格',
	'presentation': '幻灯片',
	'upload': '上传',
	'upload a file': '上传文件',
	'tag selected objects': '标签选中对象',
	'delete': '删除',
	'empty trash can': '清空回收站',
	'empty trash can desc': '永久删除回收站中的所有对象',
	'delete selected objects': '删除所选对象',
	'confirm delete object': '您确定要删除所选对象？',
	'confirm delete contact': '您确定要删除此联系人？',
	'confirm delete company': '您确定要删除此公司？',
	'confirm delete event': 'Are you sure you want to permanenetly delete this event? \nInvitations to this event will also be deleted. \nAfter deleting an event other users won\'t be able to see it in their calendars',
	'confirm delete file': '您确定要删除此文件？',
	'confirm delete mail content': '您确定要删除此邮件？',
	'confirm delete mail account': '您确定要删除此邮件账户？',
	'confirm delete milestone': '您确定要删除此里程碑？',
	'confirm delete chart': '您确定要删除此图表？',
	'confirm delete message': '您确定要删除此便签？',
	'confirm delete task list': '您确定要删除此任务列表及其子任务？',
	'confirm delete webpage': '您确定要删除此网址？',
	'confirm delete workspace': '您确定要删除工作区“{0}”？',
	'confirm delete project': '您确定要删除此工作区及其中相关数据（消息，任务，里程碑，文件等……）？',
	'confirm cancel work timeslot': '您确定要取消当前统计时段？',
	'more': '更多',
	'more actions': '更多操作',
	'more actions on first selected object': '对选中第一个对象的更多操作',
	'displaying files of': '显示文件第{0}到{1}项，总{2}项',
	'no files to display': '无文件',
	'no tasks to display': '无任务',
	'refresh desc': '刷新视图',
	'templates desc': '管理模板',
	'templates': '模板',
	'no users to display': '无用户',
	'fixed user': '固定用户',
	'parametric user': '参数用户',
	'string': '字符串',
	'add parameter': '添加参数',
	'edit workspace': '编辑所选工作区',
	'company': '公司',
	'companies': '公司',
	'checkin': '签入',
	'checkout': '迁出',
	'checked out by': '签出者：{0}',
	'add file checked out by': '{0}已被{1}签出',
	'extract': '解压缩',
	'extract files': '解压缩文件',
	'compress': '压缩',
	'compress selected files': '压缩所选文件',
	'add files to zip': '将文件添加至zip包',
	'new compressed file': '新建压缩文件',
	'song': '歌曲',
	'artist': '艺术家',
	'album': '专辑',
	'year': '年份',
	'playlist': '播放列表',
	'playlists': '播放列表',
	'unknown': '未知',
	'previous': '上一首',
	'play': '播放',
	'pause': '暂停',
	'stop': '停止',
	'next': '下一首',
	'mute': '静音',
	'unmute': '取消静音',
	'load from current workspace': '从当前工作区加载',
	'load playlist from file': '从文件加载播放列表',
	'save playlist to file': '将播放列表保存到文件',
	'clear playlist': '清空列表',
	'remove selected from playlist': '从播放列表中移除所选',
	'shuffle playlist': '缓存播放列表',
	'toggle loop playlist': '列表循环',
	'play this file': '播放此文件',
	'queue': '队列',
	'queue this file': '将文件放入播放队列',
	'must choose a file': '您必须选择一个文件',
	'file has no valid songs': '您选择的文件不包含可用曲目',
	'error': '错误',
	'success': '成功',
	'unexpected server response': '未知的服务器回应',
	'new tab': '新页签',
	'file revision comments required': '文件版本评论为必填项',
	'dashboard': '主页',
	'upload file': '上传文件',
	'contact': '联系人',
	'event': '事件',
	'task': '任务',
	'milestone': '里程碑',
	'refresh': '刷新',
	'author': '作者',
	'overview': '概览',
	'messages': '便签',
	'contacts': '联系人',
	'calendar': '日历',
	'tasks': '任务',
	'web pages': '网址库',
	'documents': '文档',
	'account': '账户',
	'search': '搜索',
	'webpage': '网址',
	'message': '便签',
	'workspaces': '工作区',
	'all customers': '所有客户',
	'create a workspace': '新建工作区',
	'delete selected workspace': '删除选中工作区',
	'select an object': '选择一个对象……',
	'filter': '筛选器',
	'all ws': '所有工作区',
	'all type': '所有类型',
	'all tag': '所有标签',
	'view': '查看',
	'details': '详情',
	'icons': '图标',
	'displaying objects of': '显示对象，第{0}到{1}项，总{2}项',
	'no objects to display': '无对象',
	'ok': '确定',
	'cancel': '取消',
	'add new contact': '新建联系人',
	'displaying contacts of': '显示联系人，第{0}到{1}项，总{2}项',
	'no contacts to display': '无联系人',
	'delete selected contacts': '删除所选联系人',
	'confirm delete contacts': '您确定要删除所选联系人？',
	'role': '角色',
	'tag selected contacts': '标签所选联系人',
	'department': '部门',
	'email2': '邮件二',
	'email3': '邮件三',
	'workWebsite': '工作网址',
	'workAddress': '工作地址',
	'workPhone1': '工作电话一',
	'workPhone2': '工作电话二',
	'homeWebsite': '家庭网址',
	'homeAddress': '家庭地址',
	'homePhone1': '家庭电话一',
	'homePhone2': '家庭电话二',
	'mobilePhone': '手机',
	'edit selected contact': '编辑所选联系人',
	'edit selected object': '编辑所选对象',
	'assign to project': '分派到工作区',
	'assign contact to project': '编辑联系人分派',
	'import': '导入',
	'export': '导出',
	'import/export': '导入/导出',
	'import - export': '联系人导入/导出',
	'not csv file continue': '所选文件不是csv文件。您确定要继续吗？',
	'from csv': '从csv文件',
	'from vcard': '从VCard文件',
	'to csv': '到csv文件',
	'to vcard': '到VCard文件',
	'to vcard all': '所有到VCard文件',
	'description': '描述',
	'title': '标题',
	'add new webpage': '新增网址',
	'displaying webpages of': '显示网址，第{0}到{1}项，总{2}项',
	'no webpages to display': '无网址',
	'delete selected webpages': '删除所选网址',
	'confirm delete webpages': '您确定要删除所选网址吗？',
	'tag selected webpages': '标签所选网址',
	'edit': '编辑',
	'edit selected webpage': '编辑所选网页',
	'text': '内容',
	'date': '日期',
	'add mail account': '添加邮件账户',
	'classify': '分类',
	'classify email': '邮件分类',
	'add new message': '新建便签',
	'view by account': '按账户',
	'view emails by account': '按账户查看邮件',
	'edit account': '编辑账户',
	'edit email account': '编辑邮件账户',
	'email actions': '邮件选项',
	'more email actions': '更多邮件选项',
	'view unclassified': '查看未分类',
	'view unclassified emails': '查看未分类邮件',
	'all accounts': '全部账户',
	'view all accounts': '查看全部账户',
	'hide messages': '隐藏便签',
	'show messages': '显示便签',
	'view all': '查看全部',
	'all emails': '全部邮件',
	'unclassified emails': '未分类邮件',
	'view options': '查看选项',
	'check mails': '检查邮件',
	'emails': '邮件',
	'create an email': '新建邮件',
	'checking email accounts': '正在检查邮件账户……',
	'folder': '文件夹',
	'yes': '是',
	'no': '否',
	'delete account emails': '同时删除邮件',
	'select': '选择',
	'read': '阅读',
	'classified': '分类',
	'accounts': '账户',
	'account options': '账户选项',
	'to': '发送到',
	'view by state': '按状态',
	'view by classification': '按分类',
	'outbox': '发件箱',
	'mail sent msg': '邮件已发送。',
	'send outbox': '发送发件箱',
	'send outbox title': '发送发件箱中的邮件',
	'sending outbox mails': '从发件箱发送邮件中……',
	'filter workspaces': '筛选工作区……',
	'filter tags': '筛选标签……',
	'alphabetical': '字母排列',
	'most active': '最活跃的',
	'alphabetical desc': '按字母排列',
	'most active desc': '按最活跃排列',
	'sort desc': '排列视图',
	'no objects message': '没有{0}',
	'no more objects message': '无更多“{0}”可显示',
	'no objects with tag message': '在“{1}”中没有标签为“{2}”的“{0}”',
	'objects': '对象',
	'checkout description': '编辑时锁定此文件',
	'undo checkout description': '将文件标为可用',
	'checkin description': '签入此文件的新版本',
	'created by on': '{0}创建于{1}',
	'write': '撰写',
	'write new mail': '写邮件',
	'email': '邮件',
	'attach contents': '附加内容',
	'email tab': '邮件',
	'weblink': '网址',
	'emailunclassified': '邮件',
	'file': '文件',
	'debug': '调试',
	'incomplete': '未完成',
	'complete': '完成',
	'do complete': '完成',
	'late': '之前',
	'status': '状态',
	'open link in new window': '在新窗口打开“{0}”',
	'wschooser desc from': '可用工作区',
	'wschooser desc to': '对象的工作区',
	'updated by': '更新者',
	'created by': '创建者',
	'view as dashboard': '主页查看',
	'subject': '主题',
	'add event': '添加事件',
	'next month': '下一月',
	'prev month': '上一月',
	'today': '今天',
	'pick a date': '转到',
	'month': '月',
	'month view': '月视图',
	'week': '周',
	'week view': '周视图',
	'day': '日',
	'day view': '日视图',
	'by state': '按状态',
	'view pending response': '待回复',
	'view will attend': '会参加',
	'view will not attend': '不会参加',
	'view maybe attend': '可能参加',
	'by user': '按用户',
	'add new event': '添加新事件',
	'prev': '上一个',
	'my calendar': '我的日历',
	'edit event details': '编辑事件详情',
	'duration': '有效期',
	'this field is required': '此字段必填',
	'reporting': '报表',
	'add new chart': '新建图表',
	'delete selected charts': '删除所选图表',
	'confirm delete charts': '您确定要删除所选图表吗？',
	'edit selected chart': '编辑所选图表',
	'tag selected charts': '标签所选图表',
	'displaying charts of': '显示图表，第{0}到{1}项，总{2}项',
	'no charts to display': '无图表',
	'charts': '图表',
	'unlock': '使用中',
	'lock': '可用',
	'edit this document': '编辑文档',
	'assigned to': '被分派给',
	'assign to': '分派给',
	'add subtask to': '添加子任务到“{0}”',
	'add task to': '添加任务到“{0}”',
	'add task': '添加任务',
	'add milestone': '添加里程碑',
	'add new task': '新建任务',
	'add new milestone': '新建里程碑',
	'confirm delete task': '您确定要删除这个任务及其中的所有子任务吗？',
	'due date': '截止日期',
	'milestone delete tip': '删除此里程碑',
	'milestone edit tip': '编辑此里程碑',
	'milestone check tip': '完成/打开此里程碑',
	'milestone expand tip': '显示/隐藏其中的任务',
	'milestone view tip': '里程碑：{0}（点击查看更多）',
	'task delete tip': '删除此任务',
	'task edit tip': '编辑此任务',
	'task check tip': '完成/开启此任务',
	'task expand tip': '显示/隐藏子任务',
	'task view tip': '任务：{0}（点击查看更多）',
	'task move down tip': '将任务下移',
	'dont assign': '不分派',
	'overdue': '过期',
	'active': '动态',
	'my active': '我的动态',
	'my subscribed': '我的订阅',
	'new milestone': '新里程碑',
	'new task': '新任务',
	'error adding task': '添加任务错误',
	'error adding milestone': '添加里程碑错误',
	'error fetching tasks': '获取任务错误',
	'unread emails': '未读邮件',
	'mark read': '标为已读',
	'mark unread': '标为未读',
	'from': '发件人',
	'draft': '草稿',
	'create contact or client company': '创建联系人或客户公司',
	'mail sent': '已发送邮件',
	'click to remove': '点击移动',
	'save': '保存',
	'choose a filename': '选择一个文件名',
	'rename tag': '重命名标签',
	'enter a new name for the tag': '输入新名称',
	'inbox': '收件箱',
	'sent': '发送',
	'unread': '未读',
	'remove tags': '移除标签',
	'more options': '更多选项',
	'login': '登录',
	'username': '用户名',
	'password': '密码',
	'remember me': '记住我',
	'completed': '完成',
	'notify': '通知',
	'hours worked': '已工作时数',
	'completed by': '完成者',
	'assigned by': '分派者',
	'priority': '优先级',
	'unclassified': '未分类',
	'ungrouped': '未分组',
	'unassigned': '为分派',
	'anyone': '任何人',
	'everyone': '每个人'
});
