<?php return array(
	'upgrade' => '系统升级',
	'upgrade from' => '升级自',
	'upgrade to' => '升级到',
	'upgrade from to' => '从{0}升级到{1}',
	'already upgraded' => '您的系统已经升级到最新版本：{0}',
	'back to fengoffice' => '返回系统',
	'all rights reserved' => '版权所有',
	'upgrade process log' => '升级进程日志',
	'upgrade fengoffice' => '升级系统',
	'upgrade your fengoffice installation' => '升级您的系统',
	'upgrade warning' => '警告',
	'error upgrade version must be specified' => '没有指定版本。无法继续自动升级。请稍后再试，或者尝试手动升级。',
	'error upgrade version not found' => '无效的指定版本（{0}）。无法继续自动升级。请稍后再试，或者尝试手动升级。',
	'error upgrade invalid zip url' => '无效的指定版本下载地址。无法继续自动升级。请稍后再试，或者尝试手动升级。',
	'error upgrade cannot open zip file' => '无法打开新版本的压缩包文件。无法继续自动升级。请稍后再试，或者尝试手动升级。',
	'upgrade warning desc' => '升级前请<a href="{0}" target="_blank">备份</a>您的应用！',
); ?>
